apiVersion: v1
kind: Service
metadata:
  name: msa-frontend-svc
spec:
  selector:
    app: msa-frontend
  type: NodePort
  ports:
    - nodePort: 31230
      port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: msa-usersrv-svc
spec:
  selector:
    app: msa-usersrv
  type: NodePort
  ports:
    - nodePort: 31231
      port: 8000
      protocol: TCP
      targetPort: 8000